import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head />
      <body className="min-h-full flex flex-col">
        <script
          id="accessibility-patches"
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                // Patch SVGElement.prototype.innerText to avoid crashes in the accessibility widget
                if (typeof SVGElement !== "undefined" && !("innerText" in SVGElement.prototype)) {
                  Object.defineProperty(SVGElement.prototype, "innerText", {
                    get() {
                      return this.textContent || "";
                    },
                    configurable: true,
                  });
                }
                // Patch document.addEventListener for DOMContentLoaded to support dynamic script loading after page load
                const originalAddEventListener = document.addEventListener;
                document.addEventListener = function (type, listener, options) {
                  if (type === "DOMContentLoaded" && document.readyState !== "loading") {
                    setTimeout(listener, 0);
                  } else {
                    originalAddEventListener.call(this, type, listener, options);
                  }
                };
              })();
            `
          }}
        />
        {children}
      </body>
    </html>
  );
}
